### ISSUE TITLE
RaiPlay non si avvia - Commit 4f88f89

### ISSUE THREAD

**Issue by davmann** [maxbambi/plugin.video.raitv#12]
Commit [4f88f89](https://github.com/maxbambi/plugin.video.raitv/commit/4f88f891aba9f81374e1ffbd5c6246555cdbb7b9)
L'addon RaiPlay non si avvia.
Ecco la porzione di log interessata
Grazie mille e complimenti per il tuo lavoro

`2019-11-07 13:01:03.366 T:1521476320   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.raitv/default.py", line 46, in <module>
                                                raisport_keys = cache.cacheFunction(RaiPlay().fillRaiSportKeys)
                                              File "/home/osmc/.kodi/addons/plugin.video.raitv/resources/lib/StorageServer.py", line 577, in cacheFunction
                                                ret_val = funct(*args)
                                              File "/home/osmc/.kodi/addons/plugin.video.raitv/resources/lib/raiplay.py", line 105, in fillRaiSportKeys
                                                title=dataTematica[0].split('|')[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2019-11-07 13:01:03.511 T:1714410208   ERROR: GetDirectory - Error getting plugin://plugin.video.raitv/
2019-11-07 13:01:03.512 T:1915561520   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.raitv/) failed`

**Comment by nx-99** [comment]
Vero stessi errori con l'ultima vrsione id="plugin.video.raitv"  name="Rai Play" version="3.3.5"

**Comment by maxbambi** [comment]
Ho visto che una chiave nei dati di Raisport impediva l'avvio... 
spero che con l'aggiunta di questo try except vengano bypassate le eventuali future chiavi 'zoppe'.

**Comment by nx-99** [comment]
Che rapidità, sembra ok la 3.3.9
Thank.

**Comment by maxbambi** [comment]
> Che rapidità, sembra ok la 3.3.9
> Thank.

In realtà sono errori cretini, dovuti ad incongruenze altrui. 
Basterebbe la buona pratica di gestire sempre le eccezioni per evitare che dati a cavolo marginali ti blocchino tutta l'esecuzione. 
Il problema è che è la parte meno divertente della programmazione e non si fa mai

**Comment by davmann** [comment]
@maxbambi Grazie mille!!!
E, in merito al tuo [commento](https://github.com/maxbambi/plugin.video.raitv/issues/12#issuecomment-551122467), quanto hai ragione!
