### ISSUE TITLE
Problemi con il DRM

### ISSUE THREAD

**Issue by nx-99** [maxbambi/plugin.video.raitv#25]
Vuoi riuscita a riprodurre Into the Dark, con Firefox attivando il DRM riesco a gurdarlo ma con kodi no.
Dal log vedo:

> 2020-07-21 12:21:38.814 T:140259706779392  NOTICE: Creating Demuxer
2020-07-21 12:21:38.814 T:140258504492800   DEBUG: Thread FileCache start, auto delete: false
2020-07-21 12:21:38.815 T:140258504492800    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
2020-07-21 12:21:38.849 T:140259706779392   ERROR: Open - error probing input format, https://dashaz-dc-euwe.akamaized.net/subtl_proxy/6ed6fac0-ae71-4dd7-b4be-d8921d4948b9/20200713102433_12778339.ism/manifest(format=mpd-time-csf,filter=medium_1200-2400).mpd?hdnea=st=1595326898~exp=1595327048~acl=/*~hmac=ad261e5d41c2bfa189a57c1c2f4f2768f887a8d5a5eacde8a120c5fa7a5a898b
2020-07-21 12:21:38.849 T:140259706779392   ERROR: OpenDemuxStream - Error creating demuxer
2020-07-21 12:21:38.849 T:140259706779392  NOTICE: CVideoPlayer::OnExit()

**Comment by AlessandroSpa** [comment]
No, è impossibile avviarlo. Ho reinstallato widevine senza risultati

**Comment by maxbambi** [comment]
@nx-99  Nella versione 3.4.8 il plugin dovrebbe riconoscere gli stream mpd e quindi riprodurli con inputstream adaptive

**Comment by nx-99** [comment]
Ho messo la versione 3.4.8 però mi dice : 
2020-09-06 12:23:15.663 T:140328795371264   ERROR: AddOnLog: InputStream Adaptive: Invalid license_key

**Comment by maxbambi** [comment]
@nx-99 che operazione hai fatto per generare l'errore?

**Comment by nx-99** [comment]
Provo a visionare il primo episodi di Into-the-Dark-S1E1-Il-corpo
Ma vedo 
tail -f ~/.kodi/temp/kodi.log
2020-09-06 12:44:51.461 T:140306754255040  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.raitv/?path_id=%2Fvideo%2F2020%2F07%2FInto-the-Dark-S1E1-Il-corpo-db650c51-15c7-4132-bbb6-ca02e9cd3366.json&mode=play
2020-09-06 12:44:52.325 T:140305231767296  NOTICE: Creating InputStream
2020-09-06 12:44:53.260 T:140305231767296   ERROR: AddOnLog: InputStream Adaptive: Invalid license_key
2020-09-06 12:44:53.263 T:140305231767296   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.raitv/?path_id=%2Fvideo%2F2020%2F07%2FInto-the-Dark-S1E1-Il-corpo-db650c51-15c7-4132-bbb6-ca02e9cd3366.json&mode=play]

**Comment by maxbambi** [comment]
@maxbambi, 
questo è il json associato all'episodio
```
https://www.raiplay.it/video/2020/07/Into-the-Dark-S1E1-Il-corpo-db650c51-15c7-4132-bbb6-ca02e9cd3366.json
```
e questo è il link
```
http://mediapolisvod.rai.it/relinker/relinkerServlet.htm?cont=bI3aMpPpPlussssSlashvJhssSlashwkqvyCuZ3kgeeqqEEqualeeqqEEqual
```
associato allo stream
```
https://dashaz-dc-euno.akamaized.net/subtl_proxy/6ed6fac0-ae71-4dd7-b4be-d8921d4948b9/20200713102433_12778339.ism/manifest(format=mpd-time-csf,filter=medium_1200-2400).mpd
```
Se incollo l'ultimo link in vlc, parte una riproduzione con schermo nero e ciò fa pensare che questo sia protetto da DRM
Ma nel json ci dovrebbe essere anche il link per ottenere la chiave...
Provo ad indagare aprendo da browser

**Comment by maxbambi** [comment]
@nx-99 
Con questa modifica al link 
```
https://mediapolisvod.rai.it/relinker/relinkerServlet.htm?cont=bI3aMpPpPlussssSlashvJhssSlashwkqvyCuZ3kgeeqqEEqualeeqqEEqual&output=56
```
si ottiene un output più ricco di informazioni
```
<Mediapolis>
<url type="content"><![CDATA[https://dashaz-dc-euwe.akamaized.net/subtl_proxy/6ed6fac0-ae71-4dd7-b4be-d8921d4948b9/20200713102433_12778339.ism/manifest(format=mpd-time-csf,filter=medium_1200-2400).mpd?hdnea=st=1599390389~exp=1599390539~acl=/*~hmac=76795dfa4003778d0f25fd9825ea58a64ed84e8e822c1283258723d2094e1525]]></url>
<url type="bumper"></url>
<url type="bumperend"></url>
<ct>dash_azure</ct>
<bitrate>0</bitrate>
<smooth>Y</smooth>
<is_live>N</is_live>
<description>Rai</description>
<geoprotection>Y</geoprotection>
<category>4942</category>
<plVod></plVod>
<plLive></plLive>
<logo></logo>
<poster>https://download2-geo-rai-it.akamaized.net/infocdn/Rai/DRM_Sony/12778339_snapshot.jpg</poster><duration>01:19:31</duration>
<krpano></krpano>
<channel></channel>
<ads_tecnico></ads_tecnico>
<license_url><![CDATA[{"drmLicenseUrlValues":[{"drm":"WIDEVINE","licenceUrl":"https://mediaservicerainet03.keydelivery.westeurope.media.azure.net/Widevine/?kid=5ca7736f-7e27-49fc-80b2-bde49c8c0259&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cm46bWljcm9zb2Z0OmF6dXJlOm1lZGlhc2VydmljZXM6Y29udGVudGtleWlkZW50aWZpZXIiOiI1Y2E3NzM2Zi03ZTI3LTQ5ZmMtODBiMi1iZGU0OWM4YzAyNTkiLCJpc3MiOiJodHRwOi8vcmFpcGxheSIsImF1ZCI6InVybjpyYWlwbGF5X2hkY3BfdjFfc2wxX3NkIiwiZXhwIjoxNTk5MzkwNjg5fQ.pMKkUxa5vg8Y0taM4mdEhvoTMaTM5IN33F2cLVkuXJM","name":"Widevine Token Restricted JWT HDCP_V1_SL1_SD","audience":"urn:raiplay_hdcp_v1_sl1_sd"},{"drm":"PLAYREADY","licenceUrl":"https://mediaservicerainet03.keydelivery.westeurope.media.azure.net/PlayReady/?kid=5ca7736f-7e27-49fc-80b2-bde49c8c0259&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cm46bWljcm9zb2Z0OmF6dXJlOm1lZGlhc2VydmljZXM6Y29udGVudGtleWlkZW50aWZpZXIiOiI1Y2E3NzM2Zi03ZTI3LTQ5ZmMtODBiMi1iZGU0OWM4YzAyNTkiLCJpc3MiOiJodHRwOi8vcmFpcGxheSIsImF1ZCI6InVybjpyYWlwbGF5IiwiZXhwIjoxNTk5MzkwNjg5fQ.FWrI-W-ZAcHn7_svKRfFd_NRLwdQkv4_mupiwSI0bCU","name":"Playready Token Restricted JWT","audience":"urn:raiplay"}]}]]></license_url>
<thumbs_array><![CDATA[{"shots":100,"frameHeight":81,"rowsPerStrips":5,"colsPerStrips":5,"files":["http://mediapolisvod.rai.it/relinker/relinkerServlet.htm?cont=fCIK0ZNPC8Q6rEOssSlashbbpPGgeeqqEEqualeeqqEEqual","http://mediapolisvod.rai.it/relinker/relinkerServlet.htm?cont=VZ33zMEOasufdPdJEoXg7geeqqEEqualeeqqEEqual","http://mediapolisvod.rai.it/relinker/relinkerServlet.htm?cont=QFMARYAGPxUs5pNWyv2YlQeeqqEEqualeeqqEEqual","http://mediapolisvod.rai.it/relinker/relinkerServlet.htm?cont=vrf8LZMklq0oKsrVssSlashJF31weeqqEEqualeeqqEEqual"]}]]></thumbs_array>
</Mediapolis>
``` 
compresa la nostra tanto desiderata chiave.
Si tratta ora di leggerla da codice e comunicarla a inputstream adaptive

**Comment by maxbambi** [comment]
@nx-99 prova la nuova versione 3.5.0

**Comment by nx-99** [comment]
Bene ora si vede con  la nuova versione 3.5.0

2020-09-06 16:44:06.577 T:139715815893184  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.raitv/?path_id=%2Fvideo%2F2020%2F07%2FInto-the-Dark-S1E5-Giu-3ab77126-9da8-4ad5-96a6-37a2b21f826b.json&mode=play
2020-09-06 16:44:06.626 T:139712551712512  NOTICE: Creating InputStream
2020-09-06 16:44:07.063 T:139712551712512  NOTICE: Creating Demuxer
2020-09-06 16:44:07.063 T:139712551712512  NOTICE: Opening stream: 1001 source: 256
2020-09-06 16:44:07.134 T:139712551712512  NOTICE: Creating video codec with codec id: 27
2020-09-06 16:44:07.134 T:139712551712512  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2020-09-06 16:44:07.135 T:139712551712512  NOTICE: Creating video thread
2020-09-06 16:44:07.135 T:139712551712512  NOTICE: Opening stream: 1002 source: 256
2020-09-06 16:44:07.136 T:139712593389312  NOTICE: running thread: video_thread
2020-09-06 16:44:07.240 T:139712551712512  NOTICE: Finding audio codec for: 86018
2020-09-06 16:44:07.240 T:139712551712512  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2020-09-06 16:44:07.241 T:139712551712512  NOTICE: Creating audio thread
2020-09-06 16:44:07.241 T:139712601782016  NOTICE: running thread: CVideoPlayerAudio::Process()
2020-09-06 16:44:07.760 T:139712593389312  NOTICE: VDPAU::CreateContext - creating decoder context
2020-09-06 16:44:07.766 T:139712601782016  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
2020-09-06 16:44:07.781 T:139712551712512   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-09-06 16:44:07.844 T:139712593389312   ERROR: Previous line repeats 4 times.

Gli ultimi due ERROR sembrano non aver effetto sulla visione.
Grazie.

**Comment by nx-99** [comment]
Però ho appena visto, con con la nuova versione 3.5.0, errori con nella visione dirette:
Error Type: <type 'exceptions.UnboundLocalError'>
Error Contents: local variable 'ct' referenced before assignment
Traceback (most recent call last):
File "~/.kodi/addons/plugin.video.raitv-master.version.3.5.0/default.py", line 833, in <module>
play(url, pathId)
File "~f/.kodi/addons/plugin.video.raitv-master.version.3.5.0/default.py", line 184, in play
xbmc.log("Media format: %s - License Url: %s" % (ct,key))
UnboundLocalError: local variable 'ct' referenced before assignment
 -->End of Python script error report<--

Sembra andare solo  RaiNews

**Comment by maxbambi** [comment]
@nx-99 errore banalissimo perché ho interpretato erroneamente dei blocchi if... risolto definendo all'inizio le due variabili

**Comment by nx-99** [comment]
@maxbambi Bene sia il DRM che le dirette funzionano, grazie anche per le spiegazioni che dai.
