### ISSUE TITLE
Addon crash

### ISSUE THREAD

**Issue by PiotrC1** [maxbambi/plugin.video.raitv#35]
```
2021-03-05 23:08:36.558 T:767     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'http.client.RemoteDisconnected'>
                                                   Error Contents: Remote end closed connection without response
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.raitv/default.py", line 851, in <module>
                                                       log_country()
                                                     File "/storage/.kodi/addons/plugin.video.raitv/default.py", line 755, in log_country
                                                       country = raiplay.getCountry()
                                                     File "/storage/.kodi/addons/plugin.video.raitv/resources/lib/raiplay.py", line 55, in getCountry
                                                       response = utils.checkStr(urllib2.urlopen(self.localizeUrl).read())
                                                     File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
                                                     File "/usr/lib/python3.8/urllib/request.py", line 525, in open
                                                     File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
                                                     File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
                                                     File "/usr/lib/python3.8/urllib/request.py", line 1379, in http_open
                                                     File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
                                                     File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
                                                     File "/usr/lib/python3.8/http/client.py", line 307, in begin
                                                     File "/usr/lib/python3.8/http/client.py", line 276, in _read_status
                                                   http.client.RemoteDisconnected: Remote end closed connection without response
                                                   -->End of Python script error report<--
```
Some more information:
`Linux LibreELEC 5.10.17 #1 SMP Mon Mar 1 22:21:33 EST 2021 x86_64 GNU/Linux`
```
<addon id="plugin.video.raitv"
       name="Rai Play"
       version="3.6.0"
       provider-name="Nightflyer, cttynul, maxbambi, fabpolli">
  <requires>
        <import addon="xbmc.python" version="3.0.0"/>
        <import addon="script.common.plugin.cache" version="2.6.0"/>
        <import addon="script.module.inputstreamhelper"/>
  </requires>

```
`Python 3.8.7`

**Comment by maxbambi** [comment]
@PiotrC1 what was your last operation when this exception was thrown?

**Comment by PiotrC1** [comment]
I have clicked and icon "RAI Play" on my desktop.

As I have found in Google throwing excepion is caused by changes made in recent Python versions (exception is not covered by `except urllib2.HTTPError:` line).

**Comment by maxbambi** [comment]
@PiotrC1 
try version 3.6.0.1

**Comment by PiotrC1** [comment]
Seems to be OK. Not tested very intensivelly.

**Comment by PiotrC1** [comment]
Sorry, addon again gas thrown an exception:
```
2021-03-16 17:19:43.686 T:891     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.URLError'>
                                                   Error Contents: <urlopen error _ssl.c:1108: The handshake operation timed out>
                                                   Traceback (most recent call last):
                                                     File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
                                                     File "/usr/lib/python3.8/http/client.py", line 1255, in request
                                                     File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
                                                     File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
                                                     File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
                                                     File "/usr/lib/python3.8/http/client.py", line 950, in send
                                                     File "/usr/lib/python3.8/http/client.py", line 1424, in connect
                                                     File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
                                                     File "/usr/lib/python3.8/ssl.py", line 1040, in _create
                                                     File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
                                                   socket.timeout: _ssl.c:1108: The handshake operation timed out
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.raitv/default.py", line 50, in <module>
                                                       raisport_keys = cache.cacheFunction(RaiPlay(Addon).fillRaiSportKeys)
                                                     File "/storage/.kodi/addons/script.common.plugin.cache/resources/lib/storage_server/StorageServer.py", line 623, in cacheFunction
                                                       ret_val = funct(*args)
                                                     File "/storage/.kodi/addons/plugin.video.raitv/resources/lib/raiplay.py", line 126, in fillRaiSportKeys
                                                       data = utils.checkStr(urllib2.urlopen(self.RaiSportMainUrl + l['url']).read())
                                                     File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
                                                     File "/usr/lib/python3.8/urllib/request.py", line 525, in open
                                                     File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
                                                     File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
                                                     File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
                                                     File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
                                                   urllib.error.URLError: <urlopen error _ssl.c:1108: The handshake operation timed out>
                                                   -->End of Python script error report<--
                                                   
```

**Comment by maxbambi** [comment]
@PiotrC1 
Now I hope to have cleaned all exception codes, in all files

**Comment by PiotrC1** [comment]
Sorry for disturbing, but are you sure these were all exceptions:
```
2021-03-17 21:49:46.488 T:2065    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.URLError'>
                                                   Error Contents: <urlopen error EOF occurred in violation of protocol (_ssl.c:1125)>
                                                   Traceback (most recent call last):
                                                     File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
                                                     File "/usr/lib/python3.8/http/client.py", line 1255, in request
                                                     File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
                                                     File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
                                                     File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
                                                     File "/usr/lib/python3.8/http/client.py", line 950, in send
                                                     File "/usr/lib/python3.8/http/client.py", line 1424, in connect
                                                     File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
                                                     File "/usr/lib/python3.8/ssl.py", line 1040, in _create
                                                     File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
                                                   ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.raitv/default.py", line 774, in <module>
                                                       show_tv_channels()
                                                     File "/storage/.kodi/addons/plugin.video.raitv/default.py", line 212, in show_tv_channels
                                                       onAirJson = raiplay.getOnAir()
                                                     File "/storage/.kodi/addons/plugin.video.raitv/resources/lib/raiplay.py", line 65, in getOnAir
                                                       response = json.loads(utils.checkStr(urllib2.urlopen(self.onAirUrl).read()))
                                                     File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
                                                     File "/usr/lib/python3.8/urllib/request.py", line 525, in open
                                                     File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
                                                     File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
                                                     File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
                                                     File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
                                                   urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1125)>
                                                   -->End of Python script error report<--
```
`2021-03-17 21:31:53.422 T:1621     INFO <general>: CAddonMgr::FindAddon: plugin.video.raitv v3.6.0.2 installed`

**Comment by maxbambi** [comment]
@PiotrC1 
In this case there wasn't an error of exception code, but the lack of try except ...
It is strange because, at this point the plugin simply reads a fixed json page with the list of channels
