### ISSUE TITLE
raiplay sound

### ISSUE THREAD

**Issue by marione333** [maxbambi/plugin.video.raitv#50]
Da quando c'è Raiplay Sound non funziona più il replay delle radio su questo addon. sarà integrato questo nuovo sito (Raiplay Sound) nell'Addon? ci sarà un nuovo addon? ci sono molti contenuti in podcast interessanti! sarebbe molto bello averlo. 
grazie
------
Since Raiplay Sound has existed, radio replay no longer works on this addon. will this new site (Raiplay Sound) be integrated into the Addon? will there be a new addon? there is a lot of interesting podcast content! it would be very nice to have it. 
thank you

**Comment by marione333** [comment]
ci sono novità riguardo questo nuovo nuovo sito rai?
grazie

**Comment by denics** [comment]
quando si prova a selezionare il replay di una radio si ha questo errore:

```python
2023-04-15 13:46:27.728 T:8094    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: argument "label" for method "ListItem" must be unicode or str
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.raitv/default.py", line 851, in <module>
                                                       show_replay_radio_channels(date)
                                                     File "/storage/.kodi/addons/plugin.video.raitv/default.py", line 385, in show_replay_radio_channels
                                                       liStyle = xbmcgui.ListItem(station["channel"])
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: argument "label" for method "ListItem" must be unicode or str
                                                   -->End of Python script error report<--

2023-04-15 13:46:27.806 T:8093    error <general>: GetDirectory - Error getting plugin://plugin.video.raitv/?date=15-04-2023&media=radio&mode=replay
2023-04-15 13:46:27.834 T:1043    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.raitv/?date=15-04-2023&media=radio&mode=replay) failed
```
