### ISSUE TITLE
Some channels (i.e. Rai1) do not work anymore

### ISSUE THREAD

**Issue by denics** [maxbambi/plugin.video.raitv#53]
Ciao, I am using your great plugin from France, via ProtonVPN and so far, a part from some Proton issues, everything was fine. However, since a while, some channels return 404 like Rai1. 

This is the debug:

```
2022-06-05 10:26:47.254 T:3114     INFO <general>: initializing python engine.
2022-06-05 10:26:49.176 T:3114     INFO <general>: CPythonInvoker(55, /storage/.kodi/addons/plugin.video.raitv/default.py): script successfully run
2022-06-05 10:26:49.238 T:2681     INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.raitv/?mode=play&url=https%3A%2F%2Fmediapolis.rai.it%2Frelinker%2FrelinkerServlet.htm%3Fcont%3D2606803
2022-06-05 10:26:49.921 T:3114  WARNING <general>: CPythonInvoker(55, /storage/.kodi/addons/plugin.video.raitv/default.py): the python script "/storage/.kodi/addons/plugin.video.raitv/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE
2022-06-05 10:26:49.921 T:3114     INFO <general>: Python interpreter stopped
2022-06-05 10:26:50.550 T:2681    ERROR <general>: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://raiuno1-live.akamaized.net/hls/live/598308/raiuno1/raiuno1/playlist_ma.m3u8?hdnea=st=1654417609~exp=1654417759~acl=/*~hmac=f7bf3915cf56a54018cbe96b813dc0c583da9cd879eef47275e10eb51b0d236d|User-Agent=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F84.0.4147.105+Safari%2F537.36
2022-06-05 10:26:50.551 T:3117     INFO <general>: Creating InputStream
2022-06-05 10:26:51.289 T:3117    ERROR <general>: CCurlFile::Open failed with code 404 for https://raiuno1-live.akamaized.net/hls/live/598308/raiuno1/raiuno1/playlist_ma.m3u8?hdnea=st=1654417609~exp=1654417759~acl=/*~hmac=f7bf3915cf56a54018cbe96b813dc0c583da9cd879eef47275e10eb51b0d236d:
                                                   
2022-06-05 10:26:51.291 T:3117     INFO <general>: Creating Demuxer
2022-06-05 10:26:51.889 T:3117    ERROR <general>: OpenDemuxStream - Error creating demuxer
2022-06-05 10:26:51.890 T:3117     INFO <general>: CVideoPlayer::OnExit()
2022-06-05 10:26:51.895 T:3096     INFO <general>: Deleting settings information for files plugin://plugin.video.raitv/?mode=play&url=https%3A%2F%2Fmediapolis.rai.it%2Frelinker%2FrelinkerServlet.htm%3Fcont%3D2606803
2022-06-05 10:26:51.925 T:2681     INFO <general>: CVideoPlayer::CloseFile()
2022-06-05 10:26:51.925 T:2681     INFO <general>: VideoPlayer: waiting for threads to exit
2022-06-05 10:26:51.925 T:2681     INFO <general>: VideoPlayer: finished waiting
```
I recently wrote a patch for the radio for Mycroft and I realized that very recently the relinker changed the position of few json around https://github.com/denics/skill-npr-news/commit/dfecf83ab7ed9563b7c894472a885cd279d41c10

Best regards,
Denis

**Comment by maxbambi** [comment]
Hi @denics, I haven't been received any notification from this repository for some months, so I have only read today your post.
I'm in Italy and streaming is working in my exprerience.
Other people who use VPN, have written me that there are some problems (in particular that streams end very soon), but I don't know how to solve them.
Can you see streams from raiplay.it in a normal browser through VPN?
If yes, could you send me informations from developer tool in the browser?

**Comment by denics** [comment]
Ciao @maxbambi sorry to jump in this late.
I have tested with the VPN (protonvpn via TCP) with other channels, i.e. 24Horas using Simple IPTV and I have no problems at all. With RaiPlay the image freeze very often, and we get a lot of errors. With the VPN raiplay.it works fine.

```
2023-04-01 13:31:19.995 T:1050     info <general>: VideoPlayer::OpenFile: plugin://plugin.video.raitv/?mode=play&url=https%3A%2F%2Fmediapolis.rai.it%2Frelinker%2FrelinkerServlet.htm%3Fcont%3D2606803
2023-04-01 13:31:20.151 T:12652   error <general>: GetDirectory - Error getting -
2023-04-01 13:31:20.600 T:12742    info <general>: Creating InputStream
2023-04-01 13:31:21.233 T:12742    info <general>: Creating Demuxer
2023-04-01 13:31:48.352 T:12742    info <general>: Opening stream: 4 source: 256
2023-04-01 13:31:48.353 T:12742    info <general>: [WHITELIST] Searching the whitelist for: width: 1280, height: 720, fps: 25.000, 3D: false
2023-04-01 13:31:48.354 T:12742    info <general>: Display resolution ADJUST : 1920x1080 @ 25.000000 Hz (30) (weight: -nan)
2023-04-01 13:31:48.381 T:1050     info <general>: VideoPlayer: OnLostDisplay received
2023-04-01 13:31:48.381 T:1050  warning <general>: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
2023-04-01 13:31:48.381 T:1050  warning <general>: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
2023-04-01 13:31:48.381 T:1050     info <general>: GLES: Maximum texture width: 4096
2023-04-01 13:31:48.423 T:12742    info <general>: Creating video codec with codec id: 27
2023-04-01 13:31:48.423 T:12742    info <general>: CDVDVideoCodecDRMPRIME::Open - using decoder V4L2 mem2mem H.264 decoder wrapper
2023-04-01 13:31:48.437 T:12742    info <general>: Creating video thread
2023-04-01 13:31:48.438 T:12811    info <general>: running thread: video_thread
2023-04-01 13:31:48.438 T:12742    info <general>: Opening stream: 0 source: 256
2023-04-01 13:31:48.438 T:12742    info <general>: Finding audio codec for: 86018
2023-04-01 13:31:48.439 T:12742    info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2023-04-01 13:31:48.439 T:12742    info <general>: OpenStream: Allowing max Out-Of-Sync Value of 10 ms
2023-04-01 13:31:48.439 T:12742    info <general>: Creating audio thread
2023-04-01 13:31:48.439 T:12812    info <general>: running thread: CVideoPlayerAudio::Process()
2023-04-01 13:31:48.502 T:1050     info <general>: VideoPlayer: OnResetDisplay received
2023-04-01 13:31:48.546 T:12812    info <general>: CVideoPlayerAudio: display reset occurred, checking for passthrough
2023-04-01 13:31:48.549 T:12812    info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2023-04-01 13:31:48.549 T:12812    info <general>: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
2023-04-01 13:31:48.550 T:1057     info <general>: CActiveAE::ApplySettings - Forcing samplerate to 48000
2023-04-01 13:31:51.306 T:12652   error <general>: GetDirectory - Error getting -
2023-04-01 13:31:51.308 T:1050     info <general>: [WHITELIST] Searching the whitelist for: width: 1280, height: 720, fps: 25.000, 3D: false
2023-04-01 13:31:51.311 T:1050     info <general>: Display resolution ADJUST : 1920x1080 @ 25.000000 Hz (30) (weight: 0.000)
2023-04-01 13:31:54.282 T:1057  warning <general>: ActiveAE - large audio sync error: -2151.790943
2023-04-01 13:31:54.299 T:1057  warning <general>: ActiveAE - large audio sync error: -1951.790535
2023-04-01 13:31:54.349 T:12812    info <general>: CVideoPlayerAudio::Process - stream stalled
2023-04-01 13:31:58.122 T:12811   error <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: End of file (-541478725)
2023-04-01 13:32:34.344 T:12812    info <general>: Skipped 18 duplicate messages..
2023-04-01 13:32:34.344 T:12812    info <general>: ProcessDecoderOutput: Changed max allowed Out-Of-Sync value to 16 ms due self-learning
2023-04-01 13:32:34.346 T:1057  warning <general>: ActiveAE - large audio sync error: -5749.867741
2023-04-01 13:32:34.347 T:1057  warning <general>: ActiveAE - large audio sync error: -5749.867445
2023-04-01 13:32:34.348 T:1057  warning <general>: ActiveAE - large audio sync error: -5749.867797
2023-04-01 13:32:34.349 T:1057  warning <general>: ActiveAE - large audio sync error: -5749.867593
2023-04-01 13:32:34.351 T:1057  warning <general>: ActiveAE - large audio sync error: -5749.867704
2023-04-01 13:32:34.421 T:12811   error <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: End of file (-541478725)
2023-04-01 13:32:34.426 T:1057     info <general>: Skipped 186 duplicate messages..
2023-04-01 13:32:34.426 T:1057  warning <general>: ActiveAE - large audio sync error: -5798.858648
2023-04-01 13:32:34.426 T:12811   error <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: End of file (-541478725)
2023-04-01 13:32:34.476 T:1057     info <general>: Skipped 1 duplicate messages..
2023-04-01 13:32:34.476 T:1057  warning <general>: ActiveAE - large audio sync error: -5799.836907
2023-04-01 13:32:34.476 T:1057  warning <general>: ActiveAE - large audio sync error: -5749.835629
2023-04-01 13:32:34.476 T:1057  warning <general>: ActiveAE - large audio sync error: -5699.835537
2023-04-01 13:32:36.589 T:12812    info <general>: CVideoPlayerAudio::Process - stream stalled
2023-04-01 13:32:38.519 T:12811   error <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: End of file (-541478725)
2023-04-01 13:32:38.520 T:1057  warning <general>: ActiveAE - large audio sync error: -1552.143207
2023-04-01 13:32:38.520 T:12811   error <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: End of file (-541478725)
2023-04-01 13:32:38.521 T:1057     info <general>: Skipped 1 duplicate messages..
2023-04-01 13:32:38.521 T:1057  warning <general>: ActiveAE - large audio sync error: -1591.257541
2023-04-01 13:32:38.521 T:1057  warning <general>: ActiveAE - large audio sync error: -1592.143132
2023-04-01 13:32:38.522 T:12811   error <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: End of file (-541478725)
2023-04-01 13:32:38.525 T:1057     info <general>: Skipped 2 duplicate messages..
2023-04-01 13:32:38.525 T:1057  warning <general>: ActiveAE - large audio sync error: -1591.143022
2023-04-01 13:32:38.525 T:12811   error <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: End of file (-541478725)
2023-04-01 13:32:38.526 T:1057  warning <general>: ActiveAE - large audio sync error: -1642.087726
2023-04-01 13:32:38.526 T:12811   error <general>: CDVDVideoCodecDRMPRIME::AddData - send packet failed: End of file (-541478725)
2023-04-01 13:32:38.576 T:1057     info <general>: Skipped 1 duplicate messages..
2023-04-01 13:33:54.043 T:12980    info <general>: Deleting settings information for files plugin://plugin.video.raitv/?mode=play&url=https%3A%2F%2Fmediapolis.rai.it%2Frelinker%2FrelinkerServlet.htm%3Fcont%3D2606803
2023-04-01 13:33:54.053 T:1050     info <general>: VideoPlayer: finished waiting
2023-04-01 13:33:54.053 T:1050     info <general>: CVideoPlayer::CloseFile()
2023-04-01 13:33:54.053 T:1050     info <general>: VideoPlayer: waiting for threads to exit
2023-04-01 13:33:54.053 T:1050     info <general>: VideoPlayer: finished waiting
2023-04-01 13:33:54.156 T:12980   error <general>: GetDirectory - Error getting -
2023-04-01 13:34:34.534 T:13071    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - GetChannelStreamProperties - Live Stream URL: http://mediapolisevent.rai.it/relinker/relinkerServlet.htm?cont=2606803
2023-04-01 13:34:34.554 T:1050     info <general>: VideoPlayer::OpenFile: pvr://channels/tv/All%20channels/3@pvr.iptvsimple_172347587.pvr
2023-04-01 13:34:34.556 T:13079    info <general>: Creating InputStream
2023-04-01 13:34:34.805 T:13079    info <general>: Creating Demuxer
2023-04-01 13:34:34.807 T:13079   error <general>: Open - error probing input format, http://mediapolisevent.rai.it/relinker/relinkerServlet.htm?cont=2606803
2023-04-01 13:34:34.807 T:13079   error <general>: OpenDemuxStream - Error creating demuxer
2023-04-01 13:34:34.807 T:13079    info <general>: CVideoPlayer::OnExit()
2023-04-01 13:34:34.812 T:12983    info <general>: Deleting settings information for files pvr://channels/tv/All%20channels/3@pvr.iptvsimple_172347587.pvr
2023-04-01 13:34:34.816 T:1050     info <general>: CVideoPlayer::CloseFile()
2023-04-01 13:34:34.816 T:1050     info <general>: VideoPlayer: waiting for threads to exit
2023-04-01 13:34:34.816 T:1050     info <general>: VideoPlayer: finished waiting
2023-04-01 13:34:34.818 T:12983   error <general>: GetDirectory - Error getting -
2023-04-01 13:34:39.565 T:13091    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - GetChannelStreamProperties - Live Stream URL: https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=308718
2023-04-01 13:34:39.584 T:1050     info <general>: VideoPlayer::OpenFile: pvr://channels/tv/All%20channels/3@pvr.iptvsimple_1594803689.pvr
2023-04-01 13:34:39.585 T:13100    info <general>: Creating InputStream
2023-04-01 13:34:39.633 T:12980   error <general>: GetDirectory - Error getting -
2023-04-01 13:34:39.822 T:13100    info <general>: Creating Demuxer
2023-04-01 13:34:39.824 T:13100   error <general>: Open - error probing input format, https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=308718
2023-04-01 13:34:39.824 T:13100   error <general>: OpenDemuxStream - Error creating demuxer
2023-04-01 13:34:39.824 T:13100    info <general>: CVideoPlayer::OnExit()
2023-04-01 13:34:39.829 T:12980    info <general>: Deleting settings information for files pvr://channels/tv/All%20channels/3@pvr.iptvsimple_1594803689.pvr
2023-04-01 13:34:39.848 T:1050     info <general>: CVideoPlayer::CloseFile()
2023-04-01 13:34:39.848 T:1050     info <general>: VideoPlayer: waiting for threads to exit
2023-04-01 13:34:39.848 T:1050     info <general>: VideoPlayer: finished waiting
2023-04-01 13:34:39.850 T:12979   error <general>: GetDirectory - Error getting -
2023-04-01 13:34:43.653 T:13112 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-04-01 13:34:43.654 T:13112 warning <general>: ListItem.setCast() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setCast().
2023-04-01 13:34:43.654 T:13112 warning <general>: ListItem.setRating() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setRating().
2023-04-01 13:34:43.654 T:13112    info <general>: Skipped 1 duplicate messages..
2023-04-01 13:34:43.654 T:13112 warning <general>: "resumetime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-04-01 13:34:43.654 T:13112 warning <general>: "totaltime" in ListItem.setProperty() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.setResumePoint().
2023-04-01 13:34:43.655 T:13112 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVi
deo.addSubtitleStream().
2023-04-01 13:34:43.655 T:13112    info <general>: Skipped 5 duplicate messages..
```

as you can see, I first try to use your plugin, then I move to simple iptv with the same result :(

**Comment by denics** [comment]
non so se possa aiutare, ma ho questo errore, sempre via VPN:

```
2023-04-15 13:58:28.507 T:8602    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: string index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.raitv/default.py", line 905, in <module>
                                                       play(url, pathId)
                                                     File "/storage/.kodi/addons/plugin.video.raitv/default.py", line 183, in play
                                                       if url[0] == "/":
                                                          ~~~^^^
                                                   IndexError: string index out of range
                                                   -->End of Python script error report<--

2023-04-15 13:58:28.592 T:1043    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.raitv/?mode=play&path_id=%2Fvideo%2F2023%2F04%2FTg2-ore-1300-del-15042023-422e8672-e5ad-4873-a8f2-dd6a2235437a.html%3Fjson]
2023-04-15 13:58:28.592 T:1043     info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
```

**Comment by denics** [comment]
e anche questo:

```
2023-04-15 14:03:49.210 T:9205    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.URLError'>
                                                   Error Contents: <urlopen error TLS/SSL connection has been closed (EOF) (_ssl.c:992)>
                                                   Traceback (most recent call last):
                                                     File "/usr/lib/python3.11/urllib/request.py", line 1348, in do_open
                                                     File "/usr/lib/python3.11/http/client.py", line 1282, in request
                                                     File "/usr/lib/python3.11/http/client.py", line 1328, in _send_request
                                                     File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
                                                     File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
                                                     File "/usr/lib/python3.11/http/client.py", line 975, in send
                                                     File "/usr/lib/python3.11/http/client.py", line 1454, in connect
                                                     File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
                                                     File "/usr/lib/python3.11/ssl.py", line 1075, in _create
                                                     File "/usr/lib/python3.11/ssl.py", line 1346, in do_handshake
                                                   ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:992)

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.raitv/default.py", line 854, in <module>
                                                       show_replay_tv_epg(date, channelId)
                                                     File "/storage/.kodi/addons/plugin.video.raitv/default.py", line 396, in show_replay_tv_epg
                                                       programmes = raiplay.getProgrammes(channelId, date)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.raitv/resources/lib/raiplay.py", line 198, in getProgrammes
                                                       response = json.loads(utils.checkStr(urllib2.urlopen(url).read()))
                                                                                            ^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
                                                     File "/usr/lib/python3.11/urllib/request.py", line 519, in open
                                                     File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
                                                     File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
                                                     File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
                                                     File "/usr/lib/python3.11/urllib/request.py", line 1351, in do_open
                                                   urllib.error.URLError: <urlopen error TLS/SSL connection has been closed (EOF) (_ssl.c:992)>
                                                   -->End of Python script error report<--

2023-04-15 14:03:49.300 T:9204    error <general>: GetDirectory - Error getting plugin://plugin.video.raitv/?channel_id=Rai%202&date=15-04-2023&media=tv&mode=replay
2023-04-15 14:03:49.323 T:1043    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.raitv/?channel_id=Rai%202&date=15-04-2023&media=tv&mode=replay) failed
```
