### ISSUE TITLE
Kodi 18

### ISSUE THREAD

**Issue by Lanternius74** [maxbambi/plugin.video.raitv#65]
Ciao, ho visto che hai effettuato dei fix con la versione 3.9.3 in matrix. Io uso la versione per kodi 18, la master, ma l'ultimo fix che hai fatto non funziona, mi dice che ha problemi con il phyton 3.0.0, immagino che in addon.xml non sia corretta la versione di phyton che nella vecchia release era 2.25.0. Ho provato a modificare quella riga di codice ma poi se provo ad installare mi dice errore installazione fallita.

**Comment by maxbambi** [comment]
@Lanternius74 ho provato a correggere addon.xml. prova a riscaricare

**Comment by Lanternius74** [comment]
Ciao, ho provato la tua modifica, ora si installa ma non parte, da un errore, ti metto sotto il log dell'errore:
2023-03-26 10:27:36.998 T:22996   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\u2019' in position 25: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.raitv/default.py", line 50, in <module>
                                                raisport_keys = cache.cacheFunction(RaiPlay(Addon).fillRaiSportKeys)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.common.plugin.cache/resources/lib/storage_server/StorageServer.py", line 628, in cacheFunction
                                                ret_val = funct(*args)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.raitv/resources/lib/raiplay.py", line 106, in fillRaiSportKeys
                                                xbmc.log("Raisport: aggiunto %s" % (subcategName+"|"+subcategCode) )
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 25: ordinal not in range(128)
                                            -->End of Python script error report<--
2023-03-26 10:27:37.054 T:22993   ERROR: GetDirectory - Error getting plugin://plugin.video.raitv/
2023-03-26 10:27:37.088 T:22874   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.raitv/) failed

**Comment by maxbambi** [comment]
@Lanternius74 Potresti provare a commentare la riga 106 del file raiplay.it (tanto non serve a nulla per il funzionamento) e vedere se invece il resto funziona?

**Comment by Lanternius74** [comment]
Ciao, commentando la linea 106 del file raiplay.py l'addon non parte e l'errore cambia nel seguente:

2023-03-28 20:32:07.912 T:15071   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xf1' in position 32: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.raitv/default.py", line 50, in <module>
                                                raisport_keys = cache.cacheFunction(RaiPlay(Addon).fillRaiSportKeys)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.common.plugin.cache/resources/lib/storage_server/StorageServer.py", line 628, in cacheFunction
                                                ret_val = funct(*args)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.raitv/resources/lib/raiplay.py", line 109, in fillRaiSportKeys
                                                xbmc.log("Raisport: aggiunto %s" % subcategName )
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 32: ordinal not in range(128)

**Comment by maxbambi** [comment]
@Lanternius74 non mi ricordo più se ho corretto questa parte o l'app dà ancora errori sulla versione per kodi 18
