### ISSUE TITLE
On Demand TV Shows search find unplayable results

### ISSUE THREAD

**Issue by d1nuc0m** [maxbambi/plugin.video.raitv#68]
I have the opposite problem of #67 
Searching for "cobra" [on RaiPlay website](https://www.raiplay.it/ricerca.html?q=cobra)y returns five videos, while on the addon the search in "On Demand TV Shows" finds a match for _Squadra Speciale Cobra 11_ . Trying to reproduce the lattert leads to "Rai Play Error. Check the log for more information" because of a HTTP 404.

The relevant part of the log is here, keypress omitted for clarity:

<details>

```
2023-05-29 13:56:07.583 T:20891   debug <general>: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.raitv/default.py): the source file to load is "/storage/.kodi/addons/plugin.video.raitv/default.py"
2023-05-29 13:56:07.583 T:20891   debug <general>: CPythonInvoker(17): default python path:
2023-05-29 13:56:07.583 T:20891   debug <general>: CPythonInvoker(17):   /usr/lib/python311.zip
2023-05-29 13:56:07.583 T:20891   debug <general>: CPythonInvoker(17):   /usr/lib/python3.11
2023-05-29 13:56:07.583 T:20891   debug <general>: CPythonInvoker(17):   /usr/lib/python3.11/lib-dynload
2023-05-29 13:56:07.583 T:20891   debug <general>: CPythonInvoker(17):   /usr/lib/python3.11/site-packages
2023-05-29 13:56:07.583 T:20891   debug <general>: CPythonInvoker(17): adding path:
2023-05-29 13:56:07.583 T:20891   debug <general>: CPythonInvoker(17):  /storage/.kodi/addons/plugin.video.raitv
2023-05-29 13:56:07.583 T:20891   debug <general>: CPythonInvoker(17):  /storage/.kodi/addons/script.common.plugin.cache/resources/lib/storage_server/
2023-05-29 13:56:07.583 T:20891   debug <general>: CPythonInvoker(17):  /storage/.kodi/addons/script.module.inputstreamhelper/lib
2023-05-29 13:56:07.583 T:20891   debug <general>: CPythonInvoker(17): adding args:
2023-05-29 13:56:07.583 T:20891   debug <general>: CPythonInvoker(17):  plugin://plugin.video.raitv/
2023-05-29 13:56:07.583 T:20891   debug <general>: CPythonInvoker(17):  9
2023-05-29 13:56:07.583 T:20891   debug <general>: CPythonInvoker(17):  ?mode=ondemand_search_by_name
2023-05-29 13:56:07.583 T:20891   debug <general>: CPythonInvoker(17):  resume:false
2023-05-29 13:56:07.583 T:20891   debug <general>: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.raitv/default.py): entering source directory /storage/.kodi/addons/plugin.video.raitv
2023-05-29 13:56:07.583 T:20891   debug <general>: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.raitv/default.py): instantiating addon using automatically obtained id of "plugin.video.raitv" dependent on version 3.0.0 of the xbmc.python api
2023-05-29 13:56:07.646 T:843     debug <general>: ------ Window Init (DialogBusy.xml) ------
2023-05-29 13:56:07.670 T:872     debug <general>: PushCecKeypress - received key  b duration 128
2023-05-29 13:56:08.845 T:843     debug <general>: ------ Window Init (DialogKeyboard.xml) ------


[OMITTED SEARCH KEYPRESS]


2023-05-29 13:56:28.084 T:843     debug <general>: ------ Window Deinit (DialogKeyboard.xml) ------
2023-05-29 13:56:28.146 T:20891   debug <general>: Searching for programme: cobra
2023-05-29 13:56:29.413 T:20890   debug <general>: Thread waiting 3462394496 terminating
2023-05-29 13:56:29.427 T:20891   debug <general>: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.raitv/default.py): script successfully run
2023-05-29 13:56:29.428 T:20891   debug <general>: onExecutionDone(17, /storage/.kodi/addons/plugin.video.raitv/default.py)
2023-05-29 13:56:29.444 T:843     debug <general>: ------ Window Deinit (DialogBusy.xml) ------
2023-05-29 13:56:29.445 T:843     debug <general>: Saving fileitems [plugin://plugin.video.raitv/?mode=ondemand_search_by_name]
2023-05-29 13:56:29.445 T:843     debug <general>:   -- items: 1, sort method: 0, ascending: false
2023-05-29 13:56:29.450 T:20892   debug <general>: Thread BackgroundLoader start, auto delete: false
2023-05-29 13:56:29.456 T:20882   debug <general>: ffmpeg[0x50dc390]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
2023-05-29 13:56:29.457 T:20892   debug <general>: Thread BackgroundLoader 3230638720 terminating
2023-05-29 13:56:29.505 T:20891   debug <general>: Python interpreter stopped
2023-05-29 13:56:29.506 T:20891   debug <general>: Thread LanguageInvoker 3559912064 terminating
2023-05-29 13:56:30.498 T:872     debug <general>: PushCecKeypress - received key  b duration 0
2023-05-29 13:56:30.511 T:843     debug <general>: HandleKey: 11 (0xb, obc244) pressed, window 10025, action is Select
2023-05-29 13:56:30.512 T:843     debug <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.video.raitv/?mode=ondemand&path_id=http%3a%2f%2fwww.rai.it%2fraiplay%2fprogrammi%2fsquadraspecialecobra11.json&sub_type=PLR%20programma%20Page)
2023-05-29 13:56:30.512 T:843     debug <general>:   ParentPath = [plugin://plugin.video.raitv/?mode=ondemand_search_by_name]
2023-05-29 13:56:30.512 T:20893   debug <general>: Thread waiting start, auto delete: false
2023-05-29 13:56:30.518 T:20884   debug <general>: CAddonDatabase::SetLastUsed[plugin.video.raitv] took 6 ms
2023-05-29 13:56:30.518 T:20893   debug <general>: CScriptRunner: running add-on script Rai Play('plugin://plugin.video.raitv/', '10', '?mode=ondemand&path_id=http%3a%2f%2fwww.rai.it%2fraiplay%2fprogrammi%2fsquadraspecialecobra11.json&sub_type=PLR%20programma%20Page')
2023-05-29 13:56:30.518 T:20894   debug <general>: Thread LanguageInvoker start, auto delete: false
2023-05-29 13:56:30.519 T:20894   debug <general>: initializing python engine.
2023-05-29 13:56:30.519 T:20894   debug <general>: CPythonInvoker(18, /storage/.kodi/addons/plugin.video.raitv/default.py): start processing
2023-05-29 13:56:30.543 T:20894   debug <general>: -->Python Interpreter Initialized<--
2023-05-29 13:56:30.543 T:20894   debug <general>:

2023-05-29 13:56:30.543 T:20894   debug <general>: CPythonInvoker(18, /storage/.kodi/addons/plugin.video.raitv/default.py): the source file to load is "/storage/.kodi/addons/plugin.video.raitv/default.py"
2023-05-29 13:56:30.543 T:20894   debug <general>: CPythonInvoker(18): default python path:
2023-05-29 13:56:30.543 T:20894   debug <general>: CPythonInvoker(18):   /usr/lib/python311.zip
2023-05-29 13:56:30.543 T:20894   debug <general>: CPythonInvoker(18):   /usr/lib/python3.11
2023-05-29 13:56:30.543 T:20894   debug <general>: CPythonInvoker(18):   /usr/lib/python3.11/lib-dynload
2023-05-29 13:56:30.543 T:20894   debug <general>: CPythonInvoker(18):   /usr/lib/python3.11/site-packages
2023-05-29 13:56:30.543 T:20894   debug <general>: CPythonInvoker(18): adding path:
2023-05-29 13:56:30.543 T:20894   debug <general>: CPythonInvoker(18):  /storage/.kodi/addons/plugin.video.raitv
2023-05-29 13:56:30.543 T:20894   debug <general>: CPythonInvoker(18):  /storage/.kodi/addons/script.common.plugin.cache/resources/lib/storage_server/
2023-05-29 13:56:30.543 T:20894   debug <general>: CPythonInvoker(18):  /storage/.kodi/addons/script.module.inputstreamhelper/lib
2023-05-29 13:56:30.543 T:20894   debug <general>: CPythonInvoker(18): adding args:
2023-05-29 13:56:30.543 T:20894   debug <general>: CPythonInvoker(18):  plugin://plugin.video.raitv/
2023-05-29 13:56:30.543 T:20894   debug <general>: CPythonInvoker(18):  10
2023-05-29 13:56:30.543 T:20894   debug <general>: CPythonInvoker(18):  ?mode=ondemand&path_id=http%3a%2f%2fwww.rai.it%2fraiplay%2fprogrammi%2fsquadraspecialecobra11.json&sub_type=PLR%20programma%20Page
2023-05-29 13:56:30.543 T:20894   debug <general>: CPythonInvoker(18):  resume:false
2023-05-29 13:56:30.543 T:20894   debug <general>: CPythonInvoker(18, /storage/.kodi/addons/plugin.video.raitv/default.py): entering source directory /storage/.kodi/addons/plugin.video.raitv
2023-05-29 13:56:30.543 T:20894   debug <general>: CPythonInvoker(18, /storage/.kodi/addons/plugin.video.raitv/default.py): instantiating addon using automatically obtained id of "plugin.video.raitv" dependent on version 3.0.0 of the xbmc.python api
2023-05-29 13:56:30.613 T:843     debug <general>: ------ Window Init (DialogBusy.xml) ------
2023-05-29 13:56:30.623 T:872     debug <general>: PushCecKeypress - received key  b duration 125
2023-05-29 13:56:31.954 T:20894   debug <general>: Raiplay.show_ondemand_programme with PathID: http://www.rai.it/raiplay/programmi/squadraspecialecobra11.json
2023-05-29 13:56:31.956 T:20894   debug <general>: Url: http://www.rai.it/raiplay/programmi/squadraspecialecobra11.json
2023-05-29 13:56:32.533 T:20894   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: list indices must be integers or slices, not str
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.raitv/default.py", line 824, in <module>
                                                       show_ondemand_programme(pathId)
                                                     File "/storage/.kodi/addons/plugin.video.raitv/default.py", line 588, in show_ondemand_programme
                                                       if (len(programme["program_info"]["typologies"]) > 0) and programme["program_info"]["typologies"][0]["nome"] == "Film":
                                                               ~~~~~~~~~^^^^^^^^^^^^^^^^
                                                   TypeError: list indices must be integers or slices, not str
                                                   -->End of Python script error report<--

2023-05-29 13:56:32.533 T:20894   debug <general>: onExecutionDone(18, /storage/.kodi/addons/plugin.video.raitv/default.py)
2023-05-29 13:56:32.546 T:843     debug <general>: ------ Window Init (DialogNotification.xml) ------
2023-05-29 13:56:32.598 T:20894   debug <general>: Python interpreter stopped
2023-05-29 13:56:32.598 T:20894   debug <general>: Thread LanguageInvoker 3559912064 terminating
2023-05-29 13:56:32.608 T:20893   error <general>: GetDirectory - Error getting plugin://plugin.video.raitv/?mode=ondemand&path_id=http%3a%2f%2fwww.rai.it%2fraiplay%2fprogrammi%2fsquadraspecialecobra11.json&sub_type=PLR%20programma%20Page
2023-05-29 13:56:32.608 T:20893   debug <general>: Thread waiting 3462394496 terminating
2023-05-29 13:56:32.611 T:843     debug <general>: ------ Window Deinit (DialogBusy.xml) ------
2023-05-29 13:56:32.612 T:843     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.raitv/?mode=ondemand&path_id=http%3a%2f%2fwww.rai.it%2fraiplay%2fprogrammi%2fsquadraspecialecobra11.json&sub_type=PLR%20programma%20Page) failed
2023-05-29 13:56:32.612 T:843     debug <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.video.raitv/?mode=ondemand_search_by_name)
2023-05-29 13:56:32.612 T:843     debug <general>:   ParentPath = [plugin://plugin.video.raitv/?mode=ondemand]
2023-05-29 13:56:32.613 T:843     debug <general>: Loading items: 1, directory: plugin://plugin.video.raitv/?mode=ondemand_search_by_name sort method: 0, ascending: false
2023-05-29 13:56:32.655 T:20884   debug <general>: CAddonDatabase::SetLastUsed[plugin.video.raitv] took 43 ms
2023-05-29 13:56:32.659 T:20895   debug <general>: Thread BackgroundLoader start, auto delete: false
2023-05-29 13:56:32.664 T:20895   debug <general>: Thread BackgroundLoader 3230638720 terminating
2023-05-29 13:56:38.231 T:843     debug <general>: ------ Window Deinit (DialogNotification.xml) ------
```

</details>

**Comment by maxbambi** [comment]
@d1nuc0m try last version with new search api

**Comment by d1nuc0m** [comment]
> @d1nuc0m try last version with new search api

@maxbambi  Version 3.8.1 works, even if it only finds season 16 (with only 5 episodes inside) and season 26 (with only 1 episode). Tbh I don't know if this is a bug or if these are the only published episodes

**Comment by maxbambi** [comment]
> > @d1nuc0m try last version with new search api
> 
> @maxbambi Version 3.8.1 works, even if it only finds season 16 (with only 5 episodes inside) and season 26 (with only 1 episode). Tbh I don't know if this is a bug or if these are the only published episodes

Compare website raiplay.it and check if  there are other episodes...

**Comment by d1nuc0m** [comment]
> > > @d1nuc0m try last version with new search api
> > 
> > 
> > @maxbambi Version 3.8.1 works, even if it only finds season 16 (with only 5 episodes inside) and season 26 (with only 1 episode). Tbh I don't know if this is a bug or if these are the only published episodes
> 
> Compare website raiplay.it and check if there are other episodes...

Done, it finds all the episodes on the site, thank you
