### ISSUE TITLE
Python error selecting "Dirette TV"

### ISSUE THREAD

**Issue by ducarpit** [maxbambi/plugin.video.raitv#70]
Hi,
i got this Python error in the kodi.log when i click on Dirette TV:

```
2023-07-26 14:28:15.087 T:12933   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnboundLocalError'>
                                                   Error Contents: local variable 'thumb' referenced before assignment
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.raitv/default.py", line 790, in <module>
                                                       show_tv_channels()
                                                     File "/home/osmc/.kodi/addons/plugin.video.raitv/default.py", line 221, in show_tv_channels
                                                       if thumb:
                                                   UnboundLocalError: local variable 'thumb' referenced before assignment
                                                   -->End of Python script error report<--
```
Is there a way to solve?
Thanks a lot
Christian

**Comment by maxbambi** [comment]
@ducarpit your version of kodi?

**Comment by ducarpit** [comment]
@maxbambi Kodi v20

**Comment by maxbambi** [comment]
@ducarpit your version of plugin? try to download last version from here

**Comment by ducarpit** [comment]
@maxbambi my RaiPlay addon version is 3.8.1

**Comment by maxbambi** [comment]
> @maxbambi my RaiPlay addon version is 3.8.1

ok... you need an updated version of plugin... use zip installation
I've made a pull request to update official repository, but it is still waiting...
