### ISSUE TITLE
Issue on RaiSport Ciclismo

### ISSUE THREAD

**Issue by Fabioamd87** [maxbambi/plugin.video.raitv#78]
when I click on RaiSport and select "Ciclismo" I get this error.

`2024-04-22 14:11:02.404 T:2352     INFO <general>: initializing python engine.
2024-04-22 14:11:04.666 T:2352    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTMLParser' object has no attribute 'unescape'
                                                   Traceback (most recent call last):
                                                     File "/home/fabio/.kodi/addons/plugin.video.raitv/default.py", line 933, in <module>
                                                       get_raisport_items(params)
                                                     File "/home/fabio/.kodi/addons/plugin.video.raitv/default.py", line 809, in get_raisport_items
                                                       title = utils.checkStr(HTMLParser.HTMLParser().unescape(title))
                                                   AttributeError: 'HTMLParser' object has no attribute 'unescape'
                                                   -->End of Python script error report<--
                                                   
2024-04-22 14:11:04.860 T:2352     INFO <general>: Python interpreter stopped
2024-04-22 14:11:04.863 T:2351    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.raitv/?dominio=RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1&key=Ciclismo%7cCategory-337deaab-e725-4cd9-bc5e-806f37cee18f&mode=raisport_item&sub_keys=%5b%7b%27title%27%3a%20%27Giro%20d%e2%80%99Italia%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27Giro%20d%e2%80%99Italia%7cCategory-4a76fb4b-44e7-43fd-8ac6-a4c646248f20%27%7d%2c%20%7b%27title%27%3a%20%27Mondiali%20su%20strada%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27Mondiali%20su%20strada%7cCategory-e81dc2c8-eb27-4c92-85d8-3ee144213c27%27%7d%2c%20%7b%27title%27%3a%20%27Tour%20de%20France%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27Tour%20de%20France%7cCategory-9d453239-7ec0-48d7-bd29-4e47f09df34c%27%7d%2c%20%7b%27title%27%3a%20%27UCI%20BMX%20Freestyle%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27UCI%20BMX%20Freestyle%7cCategory-8df06a65-8041-434c-88e6-5c02cd777830%27%7d%2c%20%7b%27title%27%3a%20%27UCI%20BMX%20Racing%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27UCI%20BMX%20Racing%7cCategory-d2fab278-e4a6-4433-ab82-9d909efbfe88%27%7d%2c%20%7b%27title%27%3a%20%27UCI%20Ciclocross%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27UCI%20Ciclocross%7cCategory-855d5d55-eaee-4c82-a643-21cde1187410%27%7d%2c%20%7b%27title%27%3a%20%27UCI%20Mountain%20Bike%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27UCI%20Mountain%20Bike%7cCategory-600f8c8b-8198-4195-9d95-80a9517ae4e9%27%7d%2c%20%7b%27title%27%3a%20%27UCI%20Track%20(Ciclismo%20su%20Pista)%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27UCI%20Track%20(Ciclismo%20su%20Pista)%7cCategory-ab755954-e4e9-48de-a687-193850f1a771%27%7d%2c%20%7b%27title%27%3a%20%27UCI%20Trials%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27UCI%20Trials%7cCategory-14a5b6c4-bb5c-4dad-932a-851f143be743%27%7d%2c%20%7b%27title%27%3a%20%27UCI%20World%20Tour%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27UCI%20World%20Tour%7cCategory-845fcf0a-9b15-47b7-aae9-e0fd49844de6%27%7d%2c%20%7b%27title%27%3a%20%27UCI%20World%20Tour%20Femminile%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27UCI%20World%20Tour%20Femminile%7cCategory-b2055454-0ed7-4325-ab62-e204e3807a22%27%7d%2c%20%7b%27title%27%3a%20%27Vuelta%20a%20Espa%c3%b1a%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27Vuelta%20a%20Espa%c3%b1a%7cCategory-206965de-440b-4d32-a12a-1b0a465c1387%27%7d%5d
2024-04-22 14:11:04.924 T:1506    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.raitv/?dominio=RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1&key=Ciclismo%7cCategory-337deaab-e725-4cd9-bc5e-806f37cee18f&mode=raisport_item&sub_keys=%5b%7b%27title%27%3a%20%27Giro%20d%e2%80%99Italia%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27Giro%20d%e2%80%99Italia%7cCategory-4a76fb4b-44e7-43fd-8ac6-a4c646248f20%27%7d%2c%20%7b%27title%27%3a%20%27Mondiali%20su%20strada%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27Mondiali%20su%20strada%7cCategory-e81dc2c8-eb27-4c92-85d8-3ee144213c27%27%7d%2c%20%7b%27title%27%3a%20%27Tour%20de%20France%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27Tour%20de%20France%7cCategory-9d453239-7ec0-48d7-bd29-4e47f09df34c%27%7d%2c%20%7b%27title%27%3a%20%27UCI%20BMX%20Freestyle%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27UCI%20BMX%20Freestyle%7cCategory-8df06a65-8041-434c-88e6-5c02cd777830%27%7d%2c%20%7b%27title%27%3a%20%27UCI%20BMX%20Racing%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27UCI%20BMX%20Racing%7cCategory-d2fab278-e4a6-4433-ab82-9d909efbfe88%27%7d%2c%20%7b%27title%27%3a%20%27UCI%20Ciclocross%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27UCI%20Ciclocross%7cCategory-855d5d55-eaee-4c82-a643-21cde1187410%27%7d%2c%20%7b%27title%27%3a%20%27UCI%20Mountain%20Bike%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27UCI%20Mountain%20Bike%7cCategory-600f8c8b-8198-4195-9d95-80a9517ae4e9%27%7d%2c%20%7b%27title%27%3a%20%27UCI%20Track%20(Ciclismo%20su%20Pista)%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27UCI%20Track%20(Ciclismo%20su%20Pista)%7cCategory-ab755954-e4e9-48de-a687-193850f1a771%27%7d%2c%20%7b%27title%27%3a%20%27UCI%20Trials%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27UCI%20Trials%7cCategory-14a5b6c4-bb5c-4dad-932a-851f143be743%27%7d%2c%20%7b%27title%27%3a%20%27UCI%20World%20Tour%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27UCI%20World%20Tour%7cCategory-845fcf0a-9b15-47b7-aae9-e0fd49844de6%27%7d%2c%20%7b%27title%27%3a%20%27UCI%20World%20Tour%20Femminile%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27UCI%20World%20Tour%20Femminile%7cCategory-b2055454-0ed7-4325-ab62-e204e3807a22%27%7d%2c%20%7b%27title%27%3a%20%27Vuelta%20a%20Espa%c3%b1a%27%2c%20%27dominio%27%3a%20%27RaiNews%7cCategory-60bbaf3f-99b8-4aac-8a6d-69a98e11bfc1%27%2c%20%27key%27%3a%20%27Vuelta%20a%20Espa%c3%b1a%7cCategory-206965de-440b-4d32-a12a-1b0a465c1387%27%7d%5d) failed
`

I am using kodi 19.4 with rpi "buster" and download the last matrix version from this repo home page.
Let me know if I need to provide more.
Thanks
Fabio

**Comment by Fabioamd87** [comment]
[update]
If I try to access with "Dirette" menu and select "Ciclismo" kodi crashes:

```
2024-04-22 14:16:10.821 T:2389     INFO <general>: initializing python engine.
2024-04-22 14:16:13.994 T:2389     INFO <general>: CPythonInvoker(13, /home/fabio/.kodi/addons/plugin.video.raitv/default.py): script successfully run
2024-04-22 14:16:14.203 T:2389     INFO <general>: Python interpreter stopped
2024-04-22 14:16:37.245 T:2395     INFO <general>: initializing python engine.
2024-04-22 14:16:44.857 T:2395     INFO <general>: CPythonInvoker(14, /home/fabio/.kodi/addons/plugin.video.raitv/default.py): script successfully run
2024-04-22 14:16:45.029 T:2395     INFO <general>: Python interpreter stopped
2024-04-22 14:16:53.289 T:2406     INFO <general>: initializing python engine.
2024-04-22 14:16:56.278 T:2406     INFO <general>: CPythonInvoker(15, /home/fabio/.kodi/addons/plugin.video.raitv/default.py): script successfully run
2024-04-22 14:16:56.570 T:2406     INFO <general>: Python interpreter stopped
2024-04-22 14:16:56.574 T:2405    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.raitv/?mode=ondemand&path_id=%2fcollezioni%2fciclismo.json&sub_type=RaiPlay%20Raccolta%20Item
2024-04-22 14:16:56.603 T:1506    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.raitv/?mode=ondemand&path_id=%2fcollezioni%2fciclismo.json&sub_type=RaiPlay%20Raccolta%20Item) failed
2024-04-22 14:16:59.388 T:1531    ERROR <general>: CAESinkALSA - snd_pcm_writei(-32) Broken pipe - trying to recover

```
